### ISSUE TITLE
Problem with Forestry mod- onBlockPlacement

### ISSUE THREAD

**Issue by zacekjakub** [MyEssentials/MyTown2#145]
Hello, when we build an automatic farm from  Forestry mod (last stable)
it normally works, but after some time (can't say how long exactly, maybe about 20mins) the server crash with the following stacktrace:

Time: 3/30/15 2:11 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at mytown.protection.Protections.onBlockPlacement(Protections.java:291)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_251_Protections_onBlockPlacement_PlaceEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69)
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535)
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
        at forestry.farming.logic.FarmableGE.plantSaplingAt(FarmableGE.java:47)
        at forestry.farming.gadgets.TileFarmPlain.plantGermling(TileFarmPlain.java:817)
        at forestry.farming.logic.FarmLogicArboreal.plantSapling(FarmLogicArboreal.java:237)
        at forestry.farming.logic.FarmLogicArboreal.maintainGermlings(FarmLogicArboreal.java:227)
        at forestry.farming.logic.FarmLogicHomogeneous.cultivate(FarmLogicHomogeneous.java:67)
        at forestry.farming.gadgets.TileFarmPlain.doCultivationPhase(TileFarmPlain.java:509)
        at forestry.farming.gadgets.TileFarmPlain.doWork(TileFarmPlain.java:468)
        at forestry.farming.gadgets.TileGearbox.updateServerSide(TileGearbox.java:89)
        at forestry.farming.gadgets.TileFarm.func_145845_h(TileFarm.java:112)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at mytown.protection.Protections.onBlockPlacement(Protections.java:291)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_251_Protections_onBlockPlacement_PlaceEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69)
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535)
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
        at forestry.farming.logic.FarmableGE.plantSaplingAt(FarmableGE.java:47)
        at forestry.farming.gadgets.TileFarmPlain.plantGermling(TileFarmPlain.java:817)
        at forestry.farming.logic.FarmLogicArboreal.plantSapling(FarmLogicArboreal.java:237)
        at forestry.farming.logic.FarmLogicArboreal.maintainGermlings(FarmLogicArboreal.java:227)
        at forestry.farming.logic.FarmLogicHomogeneous.cultivate(FarmLogicHomogeneous.java:67)
        at forestry.farming.gadgets.TileFarmPlain.doCultivationPhase(TileFarmPlain.java:509)
        at forestry.farming.gadgets.TileFarmPlain.doWork(TileFarmPlain.java:468)
        at forestry.farming.gadgets.TileGearbox.updateServerSide(TileGearbox.java:89)
        at forestry.farming.gadgets.TileFarm.func_145845_h(TileFarm.java:112)

-- Block entity being ticked --
Details:
        Name: forestry.FarmGearbox // forestry.farming.gadgets.TileGearbox
        Block type: ID #576 (tile.for.ffarm // forestry.farming.gadgets.BlockFarm)
        Block data value: 2 / 0x2 / 0b0010
        Block location: World: (-292,91,1030), Chunk: (at 12,5,6 in -19,64; contains blocks -304,0,1024 to -289,255,1039), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
        Actual block type: ID #576 (tile.for.ffarm // forestry.farming.gadgets.BlockFarm)
        Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
        Level name: world
        All players: 0 total; []
        Chunk stats: ServerChunkCache: 756 Drop: 0
        Level seed: 3553854092282337655
        Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
        Level generator options: 
        Level spawn location: World: (-38,94,679), Chunk: (at 10,5,7 in -3,42; contains blocks -48,0,672 to -33,255,687), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
        Level time: 42451325 game time, 14162671 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 129401 (now: false), thunder time: 153 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 2.6.32-042stab093.4
        Java Version: 1.8.0_31, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 740761048 bytes (706 MB) / 1418199040 bytes (1352 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 2 total; -Xms1024M -Xmx2048M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 12, tcache: 0, allocated: 15, tallocated: 103
        FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 61 mods loaded, 61 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CodeChickenCore{1.0.1.8} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TubesCore{${version}} [Tubes Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Trapcraft{v2.2.1a} [Trapcraft] ([1.7.10] Trapcraft - v2.3.0a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IC2{2.2.694-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.694-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ImmibisCore{59.0.8} [Immibis Core] (immibis-core-59.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Core{6.4.5} [BuildCraft] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Transport{6.4.5} [BC Transport] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Silicon{6.4.5} [BC Silicon] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Builders{6.4.5} [BC Builders] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Energy{6.4.5} [BC Energy] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Factory{6.4.5} [BC Factory] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        DimensionalAnchors{59.0.2} [Dimensional Anchors] (dimensional-anchor-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        DragonsRadioMod{1.6.3} [Dragon's Radio Mod] (DragonsRadioMod-MC1.7.10-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0(1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ExtrabiomesXL{3.16.0} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IC2NuclearControl{2.1.0a} [Nuclear Control 2] (IC2NuclearControl-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IGWMod{1.1.1-17} [In-Game wiki Mod] (IGW-Mod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MyTownCore{2.0} [MyTownCore] (MyEssentials-Core-1.7.10-1.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        neiintegration{1.0.3} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OCS{1.7.2} [OpenCCSensors] (openccsensors-1.7.2 .jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.4.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Core{4.5.9.60} [ProjectRed] (ProjectRed-1.7.10-4.5.9.60-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Transmission{4.5.9.60} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.9.60-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenComputers{1.5.3.10} [OpenComputers] (OpenComputers-MC1.7.10-1.5.3.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PeripheralsPlusPlus{1.2.5} [Peripherals++] (Peripherals++-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PneumaticCraft{1.6.3-65} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.3-65-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PowerConverters{1.7.10-3.0.4.46} [Power Converters] (PowerConverters-1.7.10-3.0.4.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Transportation{4.5.9.60} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.9.60-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Compatibility{4.5.9.60} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.9.60-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Integration{4.5.9.60} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.9.60-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Illumination{4.5.9.60} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.9.60-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Expansion{4.5.9.60} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.9.60-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ServerTools{1.7.10-2.2.0.79} [ServerTools] (ServerTools-CORE-1.7.10-2.2.0.79.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ServerTools-BACKUP{1.7.10-2.2.0.23} [ServerTools Backup] (ServerTools-BACKUP-1.7.10-2.2.0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TooMuchTime{2.4.0} [TooMuchTime] (TooMuchTime-1.7.10-2.4.0.B3-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Tubes{2.0.5} [Tubes] (Tubes-1.7.10-2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Tubestuff{59.0.1} [Tubestuff] (tubestuff-59.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MyTown2{1.7.10-0.26a} [MyTown 2] (MyTown2-1.7.10-0.26a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MyTown|Datasource: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 0 / 60; []
        Is Modded: Definitely; Server brand changed to 'fml,forge'

Thank you for help. :)

**Comment by AfterWind** [comment]
Old protection system. It is already fixed.

**Comment by zacekjakub** [comment]
Sorry, can't get it. Where is it fixed? In some not released version? Because I am pretty sure I have the latest version of Mytown...

**Comment by AfterWind** [comment]
It's fixed in the repository, not in any released version yet. We'll be releasing one hopefully by the end of this week. Don't worry ;)

**Comment by zacekjakub** [comment]
Ok, thank you for reply. In fact, technically the bug is not fixed right now... :) I had to remove forestry from the server because of crashes, so please release the fixed version. I really like MyTown, but we really want the forestry mod on the server as well. :)

**Comment by evernife** [comment]
use the dev version so, here the link:
https://ci.mineguild.net/job/mytown2/

**Comment by zacekjakub** [comment]
Thank you, brilliant! :)

**Comment by zacekjakub** [comment]
Ok, not so good idea, server crashed right after start and screwed up the world, so i had to use the backup. :)

**Comment by evernife** [comment]
Ty this version: https://ci.mineguild.net/job/mytown2/119/

is the one that i am using. Make a backup and try, i dont know, but i think that the you need to delete the old config file, and i am usint the cauldron version, with forge:
1.1307.06.218

If you want the cauldron link, is here:

http://tcpr.ca/cauldron

But firstt, let me take a... cof, make a backup :+1:

**Comment by AfterWind** [comment]
@zacekjakub The repo issues are always up to date with the repo itself not the last version released.
