### ISSUE TITLE
tnt crashing the server

### ISSUE THREAD

**Issue by dezil** [MyEssentials/MyTown2#337]
set TNT off outside of claim now get this every time that chunk is loaded

http://pastebin.com/LwCYUJcQ

**Comment by AfterWind** [comment]
Issue was fixed already. Try instead of 0.2.0b version of MT2 the 246 build. That should only contain the fix for it.

**Comment by dezil** [comment]
246 does not fix the issue

**Comment by legobear154** [comment]
Reopening since @dezil is still having the problem.
Crash report: http://pastebin.com/Lg3pkaVY
WildPerms Config: http://pastebin.com/DrF3GPnU
The problem looks to be getValue() returning string and us casting to boolean.
If he regenerates the config, the values are switched to JSON bools, but it won't work at all that way. Need to do some more investigation.

**Comment by AfterWind** [comment]
Oh... right. The issue should no longer be there due to the change I made with FlagTypes although there's no real stable version for it yet.

**Comment by AfterWind** [comment]
As you can see here: https://github.com/MyEssentials/MyTown2/blob/master/src/main/java/mytown/protection/eventhandlers/ExtraEventsHandler.java#L39

The conversion, although redundant, does not crash due to what `getValue` returns (a Boolean).
